name: Weekly Pytest Run

on:
  schedule:
    - cron: '30 15 * * 5' #will run every friday 9PM IST
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run Pytest
        run: pytest tests/


      - name: Send Email Notification
        if: always()  # This ensures it sends even if previous step fails
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: GitHub Actions - Pytest Run ${{ job.status }}
          to: ujjwalnegi1@gmail.com
          from: GitHub Actions <${{ secrets.EMAIL_USERNAME }}>
          body: |
            Hello Ujjwal,
            
            Your scheduled test run has completed.
            
            ✅ Status: ${{ job.status }}
            📦 Repo: ${{ github.repository }}
            🔄 Workflow: ${{ github.workflow }}
            🌿 Branch: ${{ github.ref }}
            
            Cheers,  
            GitHub Actions